name: Validar manual

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validar-html:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Comprobar edición web
        run: quarto render --to html
